---
# tasks file for config_modules

- name: Enable Kernel Scheduler bfq Module
  become: yes
  copy:
    dest: "/etc/modules-load.d/bfq.conf"
    content: |
      bfq
  tags: modules

- name: Enable Kernel Scheduler kyber Module
  become: yes
  copy:
    dest: "/etc/modules-load.d/kyber-iosched.conf"
    content: |
      kyber-iosched
  tags: modules
